name: myvertexmodel
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - shapely
  - numpy
  - matplotlib
  - dill
  - scipy
  - pytest
prefix: /home/ardati/anaconda3/envs/myvertexmodel
